package filet

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func cleanCfg() *Config {
	c := DefaultConfig()
	c.Style.BanInlineComments = true
	c.Style.BanTrailingSpace = true
	return c
}

func cleanSource(t *testing.T, name, body string) SourceFile {
	return source(t, name, body)
}

func TestCleanRemovesTrailingWhitespace(t *testing.T) {
	f := cleanSource(t, "clean.go", "package main\n\nfunc main() {\n\tx := 1   \n\ty := 2\n}\n")
	res := CleanFile(cleanCfg(), f)
	got := strings.Join(res.Lines, "\n")
	if !strings.Contains(got, "x := 1\n") {
		t.Fatalf("code was not kept:\n[%s]", got)
	}
	if strings.Contains(got, "x := 1   ") {
		t.Fatalf("trailing whitespace survived:\n[%s]", got)
	}
	if res.Stats.TrailingSpace != 1 {
		t.Fatalf("expected one trailing-space fix, got %d", res.Stats.TrailingSpace)
	}
}

func TestCleanStripsTrailingInlineComment(t *testing.T) {
	f := cleanSource(t, "clean.go", "package main\n\nfunc main() {\n\tx := 1 // why one\n}\n")
	res := CleanFile(cleanCfg(), f)
	got := strings.Join(res.Lines, "\n")
	if !strings.Contains(got, "x := 1") {
		t.Fatalf("code was not kept:\n%s", got)
	}
	if strings.Contains(got, "// why one") {
		t.Fatalf("trailing comment survived:\n%s", got)
	}
	if res.Stats.InlineComment != 1 {
		t.Fatalf("expected one inline-comment fix, got %d", res.Stats.InlineComment)
	}
}

func TestCleanLeavesHeaderAndStandaloneComment(t *testing.T) {
	f := cleanSource(t, "clean.go", "// LICENSE\n// something important\n\npackage main\n\nfunc main() {\n\t// keep me\n\tx := 1\n}\n")
	res := CleanFile(cleanCfg(), f)
	got := strings.Join(res.Lines, "\n")
	for _, keep := range []string{"// LICENSE", "// something important", "// keep me"} {
		if !strings.Contains(got, keep) {
			t.Errorf("header/standalone comment lost: %s\n%s", keep, got)
		}
	}
}

func TestCleanKeepsDirectiveComment(t *testing.T) {
	f := cleanSource(t, "clean.go", "package main\n\nfunc main() {\n\t_ = save() //nolint:errcheck  \n}\n")
	res := CleanFile(cleanCfg(), f)
	got := strings.Join(res.Lines, "\n")
	if !strings.Contains(got, "//nolint:errcheck") {
		t.Fatalf("directive comment was stripped:\n%s", got)
	}
	if strings.Contains(got, "errcheck  \n") {
		t.Fatalf("trailing whitespace after directive survived:\n%s", got)
	}
}

func TestCleanDoesNotCorruptStringLiteral(t *testing.T) {
	f := cleanSource(t, "clean.go", "func f() {\n\ts := \"https://example.com\" // note\n}\n")
	res := CleanFile(cleanCfg(), f)
	got := strings.Join(res.Lines, "\n")
	if !strings.Contains(got, "\"https://example.com\"") {
		t.Fatalf("string literal was damaged:\n%s", got)
	}
	if strings.Contains(got, "// note") {
		t.Fatalf("trailing comment survived:\n%s", got)
	}
}

func TestCleanDropsCommentedOutCode(t *testing.T) {
	f := cleanSource(t, "clean.go", "func f() {\n\t// const x = 5\n\ty := 2\n}\n")
	res := CleanFile(cleanCfg(), f)
	got := strings.Join(res.Lines, "\n")
	if strings.Contains(got, "const x = 5") {
		t.Fatalf("commented-out code survived:\n%s", got)
	}
	if !strings.Contains(got, "y := 2") {
		t.Fatalf("real code was removed:\n%s", got)
	}
	if res.Stats.CommentedCode != 1 {
		t.Fatalf("expected one commented-code fix, got %d", res.Stats.CommentedCode)
	}
}

func TestCleanKeepsSentenceComment(t *testing.T) {
	f := cleanSource(t, "clean.go", "func f() {\n\t// this does a thing.\n\tx := 1\n}\n")
	res := CleanFile(cleanCfg(), f)
	got := strings.Join(res.Lines, "\n")
	if !strings.Contains(got, "this does a thing.") {
		t.Fatalf("sentence comment was dropped:\n%s", got)
	}
}

func TestCleanSkipsGeneratedFile(t *testing.T) {
	f := cleanSource(t, "clean.go", "// Code generated by hand. DO NOT EDIT.\n\nfunc main() {\n\tx := 1 \n}\n")
	res := CleanFile(cleanCfg(), f)
	if res.Changed {
		t.Fatalf("generated file was touched: %q", strings.Join(res.Lines, "\n"))
	}
}

func TestCleanFormatsGoSource(t *testing.T) {
	f := cleanSource(t, "clean.go", "package main\nfunc main(){\n\tx:=1  \n\ty:=2\n}\n")
	res := CleanFile(cleanCfg(), f)
	got := strings.Join(res.Lines, "\n")
	if !strings.Contains(got, "x := 1") {
		t.Fatalf("misformatted code was not normalized:\n%s", got)
	}
	if strings.Contains(got, "x:=1") {
		t.Fatalf("spacing was not normalized:\n%s", got)
	}
	if res.Stats.Formatting != 1 {
		t.Fatalf("expected one formatting fix, got %d", res.Stats.Formatting)
	}
	if !res.Changed {
		t.Fatalf("formatting change was not reported as changed")
	}
}

func TestCleanFormatOffLeavesCodeAlone(t *testing.T) {
	cfg := cleanCfg()
	cfg.Format = false
	f := cleanSource(t, "clean.go", "package main\nfunc main(){\n\tx:=1\n}\n")
	res := CleanFile(cfg, f)
	if strings.Contains(strings.Join(res.Lines, "\n"), "x := 1") {
		t.Fatalf("format disabled but source was reformatted:\n%s", strings.Join(res.Lines, "\n"))
	}
	if res.Changed {
		t.Fatalf("clean reported a change with format off")
	}
}

func TestCleanFormatGivesUpOnBrokenGo(t *testing.T) {
	f := cleanSource(t, "clean.go", "package main\nfunc main() {\n\tx := 1 // note\n\tthis is not go\n}\n")
	res := CleanFile(cleanCfg(), f)
	got := strings.Join(res.Lines, "\n")
	if strings.Contains(got, "// note") {
		t.Fatalf("line fix was skipped because the file would not format:\n%s", got)
	}
	if res.Stats.Formatting != 0 {
		t.Fatalf("expected format to give up on unparseable Go, got %d", res.Stats.Formatting)
	}
}

func TestCleanFormatsOnlyGoFiles(t *testing.T) {
	cfg := cleanCfg()
	f := cleanSource(t, "clean.rs", "fn main(){\n\tlet x=1  ;\n}\n")
	res := CleanFile(cfg, f)
	if res.Changed {
		t.Fatalf("non-Go file was formatted:\n%s", strings.Join(res.Lines, "\n"))
	}
}

func TestCleanIsIdempotent(t *testing.T) {
	f := cleanSource(t, "clean.go", "func main() {\n\tx := 1 // note  \n\t// const y = 2\n}\n")
	cfg := cleanCfg()
	once := CleanFile(cfg, f)
	twice := CleanFile(cfg, SourceFile{
		Path: f.Path, Ext: f.Ext, Lines: once.Lines,
		Src: []byte(strings.Join(once.Lines, "\n")),
	})
	if twice.Changed {
		t.Fatalf("clean is not idempotent: second pass still changed")
	}
}

func TestCleanWritesOnlyChangedFile(t *testing.T) {
	dir := t.TempDir()
	a := filepath.Join(dir, "a.go")
	b := filepath.Join(dir, "b.go")
	if err := writeTemp(a, "package main\n\nfunc main() {\n\tx := 1 // note\n}\n"); err != nil {
		t.Fatal(err)
	}
	if err := writeTemp(b, "package main\n\nfunc main() {\n\ty := 2\n}\n"); err != nil {
		t.Fatal(err)
	}
	cfg := cleanCfg()
	cfg.Extensions = []string{".go"}
	cfg.root = dir
	report, err := Clean(cfg, dir, false)
	if err != nil {
		t.Fatal(err)
	}
	if report.Changed != 1 {
		t.Fatalf("expected exactly one changed file, got %d", report.Changed)
	}
	gotA, _ := os.ReadFile(a)
	if strings.Contains(string(gotA), "// note") {
		t.Fatalf("a.go was not cleaned:\n%s", gotA)
	}
	gotB, _ := os.ReadFile(b)
	if !strings.Contains(string(gotB), "y := 2") {
		t.Fatalf("b.go changed unexpectedly:\n%s", gotB)
	}
}

func TestCleanDryRunWritesNothing(t *testing.T) {
	dir := t.TempDir()
	a := filepath.Join(dir, "a.go")
	if err := writeTemp(a, "package main\n\nfunc main() {\n\tx := 1 // note\n}\n"); err != nil {
		t.Fatal(err)
	}
	cfg := cleanCfg()
	cfg.Extensions = []string{".go"}
	cfg.root = dir
	if _, err := Clean(cfg, dir, true); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(a)
	if !strings.Contains(string(got), "// note") {
		t.Fatalf("dry run modified the file:\n%s", got)
	}
}
