package filet

import (
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// SourceFile is one readable file plus everything the rules need to inspect it.
type SourceFile struct {
	Path    string
	Rel     string
	Display string
	Ext     string
	Src     []byte
	Lines   []string
}

// Scan walks target and returns every file matching the configured extensions.
func Scan(cfg *Config, target string) ([]SourceFile, error) {
	info, err := os.Stat(target)
	if err != nil {
		return nil, err
	}
	if !info.IsDir() {
		f, err := readSource(cfg, target)
		if err != nil {
			return nil, err
		}
		return []SourceFile{f}, nil
	}

	var files []SourceFile
	err = filepath.WalkDir(target, func(path string, d fs.DirEntry, err error) error {
		switch {
		case err != nil:
			return nil
		case d.IsDir():
			return skipDir(cfg, path, target, d.Name())
		case !slices.Contains(cfg.Extensions, filepath.Ext(d.Name())):
			return nil
		}
		if f, err := readSource(cfg, path); err == nil {
			files = append(files, f)
		}
		return nil
	})
	return files, err
}

func skipDir(cfg *Config, path, target, name string) error {
	if path == target {
		return nil
	}
	if slices.Contains(cfg.Ignore, name) || isHidden(name) {
		return filepath.SkipDir
	}
	return nil
}

func isHidden(name string) bool {
	return strings.HasPrefix(name, ".") && name != "." && name != ".."
}

func readSource(cfg *Config, path string) (SourceFile, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return SourceFile{}, err
	}
	return SourceFile{
		Path:    path,
		Rel:     RootRelative(cfg.root, path),
		Display: DisplayPath(path),
		Ext:     filepath.Ext(path),
		Src:     src,
		Lines:   strings.Split(strings.ReplaceAll(string(src), "\r\n", "\n"), "\n"),
	}, nil
}

var generatedBanners = []string{
	"code generated by", "do not edit", "@generated",
	"automatically generated", "autogenerated", "generated by protoc",
}

// IsGenerated reports whether a file announces itself as machine-written.
// Generators that emit no banner at all have to be listed in ignore.
func (f SourceFile) IsGenerated() bool {
	for _, l := range f.Lines[:min(len(f.Lines), 15)] {
		low := strings.ToLower(l)
		for _, banner := range generatedBanners {
			if strings.Contains(low, banner) {
				return true
			}
		}
	}
	return false
}
